// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountSettingForm: typeof import('./src/components/AccountSettingForm.vue')['default']
    ApplicationConfigurationForm: typeof import('./src/components/ApplicationConfigurationForm.vue')['default']
    BulkSendNotificationDialog: typeof import('./src/components/BulkSendNotificationDialog.vue')['default']
    BulkUploadCSVDialog: typeof import('./src/components/BulkUploadCSVDialog.vue')['default']
    ConfigurationProfileForm: typeof import('./src/components/ConfigurationProfileForm.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    copy: typeof import('./src/components/AccountSettingForm copy.vue')['default']
    DefaultLayoutWithVerticalNav: typeof import('./src/layouts/components/DefaultLayoutWithVerticalNav.vue')['default']
    DemoFormLayoutForm: typeof import('./src/components/DemoFormLayoutForm.vue')['default']
    DemoFormLayoutHorizontalForm: typeof import('./src/components/DemoFormLayoutHorizontalForm.vue')['default']
    DeviceForm: typeof import('./src/components/DeviceForm.vue')['default']
    EnrollmentProfileForm: typeof import('./src/components/EnrollmentProfileForm.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    Loading: typeof import('./src/@core/components/Loading.vue')['default']
    Menu: typeof import('./src/layouts/components/Menu.vue')['default']
    MyAccountForm: typeof import('./src/components/MyAccountForm.vue')['default']
    NavbarThemeSwitcher: typeof import('./src/layouts/components/NavbarThemeSwitcher.vue')['default']
    PageHeader: typeof import('./src/layouts/components/PageHeader.vue')['default']
    ProductForm: typeof import('./src/components/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendNotificationDialog: typeof import('./src/components/SendNotificationDialog.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    ToastBox: typeof import('./src/@core/components/ToastBox.vue')['default']
    UserProfile: typeof import('./src/layouts/components/UserProfile.vue')['default']
    VerticalNavLayout: typeof import('./src/@layouts/components/VerticalNavLayout.vue')['default']
    VerticalNavLink: typeof import('./src/@layouts/components/VerticalNavLink.vue')['default']
    VerticalNavSectionTitle: typeof import('./src/@layouts/components/VerticalNavSectionTitle.vue')['default']
  }
}
